Calling brew cask install is disabled
Calling brew cask install is disabled since 21 december 2020. Running `brew cask install telegram` gives an error: 
```
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
```

The `brew cask <command>` was deprecated in favor of `brew <command> --cask` in Homebrew 2.6.0. Now that 2.7.0 has been released, they have been disabled.